### ISSUE TITLE
Unable to fork /bin/clang.

### ISSUE THREAD

**Issue by shaikshakeel** [microsoft/retina#130] opened 2024-03-23 17:00 UTC
**Describe the bug**
While I am setting up retina in K8s infra. I am facing below error. 

```ts=2024-03-23T16:55:10.369Z level=debug caller=loader/compile.go:26 msg="Error running command" goversion=go1.21.8 os=linux arch=arm64 numcores=8 hostname=ip-10-149-82-88.ec2.internal podname=retina-agent-4hldd version=v0.0.1 apiserver=https://172.20.0.1:443 plugins=packetforward command="/bin/clang -target bpf -Wall -D__TARGET_ARCH_arm64 -g -O2 -c /go/src/github.com/microsoft/retina/pkg/plugin/packetforward/_cprog/packetforward.c -o /go/src/github.com/microsoft/retina/pkg/plugin/packetforward/packetforward_bpf.o -I/go/src/github.com/microsoft/retina/pkg/plugin/packetforward/../lib/_arm64 -I/go/src/github.com/microsoft/retina/pkg/plugin/packetforward/../lib/common/libbpf/_src" stderr= error="fork/exec /bin/clang: no such file or directory"
ts=2024-03-23T16:55:10.369Z level=info caller=server/server.go:79 msg="gracefully shutting down HTTP server..." goversion=go1.21.8 os=linux arch=arm64 numcores=8 hostname=ip-10-149-82-88.ec2.internal podname=retina-agent-4hldd version=v0.0.1 apiserver=https://172.20.0.1:443 plugins=packetforward
ts=2024-03-23T16:55:10.369Z level=info caller=server/server.go:71 msg="HTTP server stopped with err: http: Server closed" goversion=go1.21.8 os=linux arch=arm64 numcores=8 hostname=ip-10-149-82-88.ec2.internal podname=retina-agent-4hldd version=v0.0.1 apiserver=https://172.20.0.1:443 plugins=packetforward
ts=2024-03-23T16:55:10.369Z level=panic caller=controllermanager/controllermanager.go:118 msg="Error running controller manager" goversion=go1.21.8 os=linux arch=arm64 numcores=8 hostname=ip-10-149-82-88.ec2.internal podname=retina-agent-4hldd version=v0.0.1 apiserver=https://172.20.0.1:443 plugins=packetforward error="failed to reconcile plugin packetforward: fork/exec /bin/clang: no such file or directory" errorVerbose="fork/exec /bin/clang: no such file or directory\nfailed to reconcile plugin packetforward\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:169\ngithub.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:108\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197"
panic: Error running controller manager [recovered]
	panic: Error running controller manager

goroutine 102 [running]:
github.com/microsoft/retina/pkg/telemetry.TrackPanic()
	/go/src/github.com/microsoft/retina/pkg/telemetry/telemetry.go:112 +0x1e8
panic({0x1eb6b00?, 0x4000334180?})
	/usr/local/go/src/runtime/panic.go:914 +0x218
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x1?, {0x4000aaace8?, 0x0?, 0x0?})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x78
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x40002341a0, {0x400007ff00, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x2c0
go.uber.org/zap.(*Logger).Panic(0x40005f2080?, {0x25cf876?, 0x0?}, {0x400007ff00, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:284 +0x54
github.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start(0x4000cbf450, {0x298b488?, 0x400046f450?})
	/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:118 +0x22c
created by main.main in goroutine 1
	/go/src/github.com/microsoft/retina/controller/main.go:286 +0x2190
```

- OS: AmzonLinux
- Kubernetes Version: 1.28
- Host: EKS
- Retina Version: 1.0.0

I am not running any operator. for now I am running only DaemonSet and in configmap I am adding plugins 

```
config.yaml: |-
    apiServer:
      host: 0.0.0.0
      port: 10093
    logLevel: debug
    enabledPlugin: ["packetforward"]
    metricsInterval: 10
    enableTelemetry: false
    enablePodLevel: false
    remoteContext: false
    enableAnnotations: false
```

**Comment by talnetd** [comment] 2024-03-23 17:57
The same thing happening to me as well. 

`ts=2024-03-23T17:54:50.933Z level=info caller=linuxutil/linuxutil_linux.go:42 msg="Initializing linuxutil plugin..." goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:50.933Z level=info caller=pluginmanager/pluginmanager.go:122 msg="Reconciled plugin" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns name=linuxutil
ts=2024-03-23T17:54:50.933Z level=info caller=pluginmanager/pluginmanager.go:173 msg="starting plugin linuxutil" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:50.933Z level=info caller=linuxutil/linuxutil_linux.go:57 msg="Running linuxutil plugin..." goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:50.933Z level=info caller=server/server.go:69 msg="starting HTTP server... on " goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns addr=0.0.0.0:10093
ts=2024-03-23T17:54:53.434Z level=info caller=dns/dns_linux.go:89 msg="Stopped dns plugin" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:53.674Z level=info caller=dns/dns_linux.go:64 msg="Initialized dns plugin" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:53.674Z level=info caller=pluginmanager/pluginmanager.go:122 msg="Reconciled plugin" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns name=dns
ts=2024-03-23T17:54:53.674Z level=info caller=pluginmanager/pluginmanager.go:173 msg="starting plugin dns" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:53.674Z level=error caller=dns/dns_linux.go:76 msg="Failed to attach tracer" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns error="creating network tracer attachment for pid 1: opening raw socket: operation not permitted"
ts=2024-03-23T17:54:53.674Z level=info caller=linuxutil/linuxutil_linux.go:64 msg="Context is done, linuxutil will stop running" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:56.175Z level=info caller=server/server.go:79 msg="gracefully shutting down HTTP server..." goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:56.175Z level=info caller=server/server.go:71 msg="HTTP server stopped with err: http: Server closed" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-03-23T17:54:56.175Z level=panic caller=controllermanager/controllermanager.go:118 msg="Error running controller manager" goversion=go1.21.8 os=linux arch=amd64 numcores=2 hostname=kube02 podname=retina-agent-bsbx6 version=v0.0.1 apiserver=https://10.96.0.1:443 plugins=dropreason,packetforward,linuxutil,dns error="failed to reconcile plugin dropreason: context canceled" errorVerbose="context canceled\nfailed to reconcile plugin dropreason\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:169\ngithub.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:108\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"
panic: Error running controller manager [recovered]
        panic: Error running controller manager

goroutine 16 [running]:
github.com/microsoft/retina/pkg/telemetry.TrackPanic()
        /go/src/github.com/microsoft/retina/pkg/telemetry/telemetry.go:112 +0x209
panic({0x242fc60?, 0xc0004241a0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x0?, {0x0?, 0x0?, 0xc000a6aee0?})
        /go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0008b6dd0, {0xc00055f740, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc00055e2c0?, {0x2b48afa?, 0x0?}, {0xc00055f740, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:284 +0x51
github.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start(0xc000a7abe0, {0x2f057d0?, 0xc0006afb30?})
        /go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:118 +0x28c
created by main.main in goroutine 1
        /go/src/github.com/microsoft/retina/controller/main.go:286 +0x2825
~/Projects/retina (main ✔)`

Host: ubuntu 22.04.3
Kubernetes Version:  v1.28.6

**Comment by anubhabMajumdar** [comment] 2024-03-25 01:48
I can reproduce this with v0.0.1 Arm64 images and top-of-tree main. The reason is because the tools image is missing arm64 libraries, and therefore the `lib` folder copied to the agent image is missing the libraries too.

**Comment by anubhabMajumdar** [comment] 2024-03-25 18:20
Fixed the image. Please use commit https://github.com/microsoft/retina/commit/cf23ecb9a5ed25c787d1f6ec819518749dfb7774 to build an image for `arm64`. Let us know if it works. Thanks!

**Comment by wenhuwang** [comment] 2024-04-09 06:10
hello, i encountered the same problem after recompiling retina controller image locally.
Compilation environment：darwin ARM64
Running environment: 
- OS: CentOS Linux 7 (Core)
- Kernel Version: 5.4.207-1.el7.elrepo.x86_64
- Kubernetes Version: 1.22.2
- Retina Version: v0.0.5

retina agent error logs:
```
ts=2024-04-09T05:55:40.697Z level=debug caller=loader/compile.go:22 msg=Running goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns command="/bin/clang -target bpf -Wall -D__TARGET_ARCH_x86 -g -O2 -c /go/src/github.com/microsoft/retina/pkg/plugin/dropreason/_cprog/drop_reason.c -o /go/src/github.com/microsoft/retina/pkg/plugin/dropreason/kprobe_bpf.o -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../lib/_amd64 -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../lib/common/libbpf/_src -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../filter/_cprog/"
ts=2024-04-09T05:55:40.697Z level=debug caller=loader/compile.go:26 msg="Error running command" goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns command="/bin/clang -target bpf -Wall -D__TARGET_ARCH_x86 -g -O2 -c /go/src/github.com/microsoft/retina/pkg/plugin/dropreason/_cprog/drop_reason.c -o /go/src/github.com/microsoft/retina/pkg/plugin/dropreason/kprobe_bpf.o -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../lib/_amd64 -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../lib/common/libbpf/_src -I/go/src/github.com/microsoft/retina/pkg/plugin/dropreason/../filter/_cprog/" stderr= error="fork/exec /bin/clang: no such file or directory"
ts=2024-04-09T05:55:40.697Z level=info caller=linuxutil/linuxutil_linux.go:64 msg="Context is done, linuxutil will stop running" goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-04-09T05:55:40.697Z level=info caller=server/server.go:79 msg="gracefully shutting down HTTP server..." goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-04-09T05:55:40.697Z level=info caller=watchermanager/watchermanager.go:71 msg="watcher stopping..." goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns watcher_type=*apiserver.ApiServerWatcher
ts=2024-04-09T05:55:40.697Z level=info caller=watchermanager/watchermanager.go:71 msg="watcher stopping..." goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns watcher_type=*endpoint.EndpointWatcher
ts=2024-04-09T05:55:40.697Z level=info caller=server/server.go:71 msg="HTTP server stopped with err: http: Server closed" goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns
ts=2024-04-09T05:55:40.697Z level=panic caller=controllermanager/controllermanager.go:119 msg="Error running controller manager" goversion=go1.21.9 os=linux arch=amd64 numcores=48 hostname=node4 podname=retina-agent-ppjlb version=v0.0.5 apiserver=https://10.68.0.1:443 plugins=dropreason,packetforward,linuxutil,dns error="failed to reconcile plugin dropreason: fork/exec /bin/clang: no such file or directory" errorVerbose="fork/exec /bin/clang: no such file or directory\nfailed to reconcile plugin dropreason\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:169\ngithub.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:109\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"
panic: Error running controller manager

goroutine 415 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x0?, {0x0?, 0x0?, 0xc002294020?})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000a75860, {0xc001e817c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc000eaf600?, {0x2b62b8b?, 0x0?}, {0xc001e817c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:284 +0x51
github.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start(0xc0001c1180, {0x2f22170?, 0xc0005a8000?})
	/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:119 +0x28c
created by main.main in goroutine 1
	/go/src/github.com/microsoft/retina/controller/main.go:290 +0x28d0
```

and i have confirmed that the /bin/clang file exists in the retina controller image.

**Comment by wenhuwang** [comment] 2024-04-10 08:41
I think I have found the cause of the problem. Some binary files in the amd64 architecture image compiled on the arm64 architecture machine are in arm64 format.
```
root@node4:~# ll /run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/
total 156564
drwxr-xr-x 1 root root      4096 Apr  9 17:05 ./
drwxr-xr-x 1 root root      4096 Apr 10 14:47 ../
-rwxr-xr-x 1 root root 155987080 Mar 25  2022 clang*
-rwxr-xr-x 1 root root    138896 Apr  9 17:05 cp*
-rwxr-xr-x 1 root root    639424 Apr  9 17:05 ip*
-rwxr-xr-x 1 root root     90840 Apr  9 17:05 iptables-legacy*
-rwxr-xr-x 1 root root     90840 Apr  9 17:05 iptables-legacy-save*
-rwxr-xr-x 1 root root    220000 Apr  9 17:05 iptables-nft*
-rwxr-xr-x 1 root root    220000 Apr  9 17:05 iptables-nft-save*
-rwxr-xr-x 1 root root    177048 Apr  9 17:05 ss*
-rwxr-xr-x 1 root root   1273504 Apr  9 17:05 tcpdump*
-rwxr-xr-x 1 root root     35640 Apr  9 17:05 uname*
root@node4:~# file /run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/ip
/run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/ip: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=160cf18f019a288320ad790fe87fabfffe310246, for GNU/Linux 3.7.0, stripped
root@node4:~# file /run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/clang
/run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/clang: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
root@node4:~# file /run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/tcpdump
/run/containerd/io.containerd.runtime.v2.task/k8s.io/76baa97f2687e97eefffae04d9f15976df5fdc1bf15b3726013daf3e4568e948/rootfs/bin/tcpdump: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=65a8a73b191599a6431ad0826f8f309f5f08b1e8, for GNU/Linux 3.7.0, stripped
```
I think there is a problem in the [Dockerfile](https://github.com/microsoft/retina/blob/main/controller/Dockerfile.controller) and I will fix it.

Could you please assign this issues to me?

**Comment by wenhuwang** [comment] 2024-04-11 06:26
@rbtr thanks for assigned. 
Because both tcpdump and ip binaries are ARM64 format, and they are installed at  https://github.com/microsoft/retina/blob/main/controller/Dockerfile.controller#L55, so it can probably be confirmed that the architecture of the tools image is ARM64.

According to the documentation https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope, it can be know: 
- `TARGETPLATFORM` - platform of the build result. Eg linux/amd64, linux/arm/v7, windows/amd64
- `BUILDPLATFORM` - platform of the node performing the build.

So i guess `FROM --platform=$BUILDPPLATFORM` may need to be replaced `FROM --platform=$TARGETPLATFORM` in the dockerfile, and I have tested that this solves the problem

**Comment by rbtr** [comment] 2024-04-11 15:03
This sounds reasonable to me. Maybe every occurence of `--platform=` should be `$TARGETPLATFORM` _except_ the one where we are compiling the Go binaries? In that one, it's much faster to do an ARM cross-compile from an amd64 platform, for some reason.
This might also simplify the installation of dependencies because we would not need to fake the arch here? https://github.com/microsoft/retina/blob/main/controller/Dockerfile.controller#L63

@wenhuwang are you interested in opening the PR to fix this, or should someone else pick it up?

**Comment by wenhuwang** [comment] 2024-04-12 01:31
@rbtr OK, I will submit a PR to fixthis issue.

**Closed** 2024-04-17 05:13 UTC
Labels: type/bug, area/plugins, area/infra, priority/1
