### ISSUE TITLE
GOARCH=arm64 go generate is failing on x86_64

### ISSUE THREAD

**Issue by SRodi** [microsoft/retina#1046] opened 2024-11-20 16:06 UTC
## Issue
go generate for `GOARCH=arm64` is failing

```sh
❯ GOARCH=arm64 go generate ./pkg/plugin/...;                            
fork/exec /tmp/go-build4230987009/b001/exe/mockgen: exec format error
pkg/plugin/api/types.go:13: running "go": exit status 1
fork/exec /tmp/go-build1479343241/b001/exe/mockgen: exec format error
pkg/plugin/common/common_linux.go:20: running "go": exit status 1
fork/exec /tmp/go-build3235587832/b001/exe/bpf2go: exec format error
pkg/plugin/conntrack/conntrack_linux.go:22: running "go": exit status 1
fork/exec /tmp/go-build7630523/b001/exe/bpf2go: exec format error
pkg/plugin/dropreason/dropreason_linux.go:36: running "go": exit status 1
fork/exec /tmp/go-build2414488603/b001/exe/bpf2go: exec format error
pkg/plugin/filter/filter_map_linux.go:23: running "go": exit status 1
fork/exec /tmp/go-build1515059695/b001/exe/mockgen: exec format error
pkg/plugin/infiniband/types_linux.go:17: running "go": exit status 1
fork/exec /tmp/go-build2004312046/b001/exe/mockgen: exec format error
pkg/plugin/linuxutil/types_linux.go:16: running "go": exit status 1
fork/exec /tmp/go-build396399719/b001/exe/bpf2go: exec format error
pkg/plugin/packetforward/packetforward_linux.go:31: running "go": exit status 1
fork/exec /tmp/go-build309799770/b001/exe/bpf2go: exec format error
pkg/plugin/packetparser/packetparser_linux.go:52: running "go": exit status 1
```

## Environment
```
❯ uname -a                 
Linux Simone 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

❯ go version                                      
go version go1.23.1 linux/amd64

❯ which clang
which llvm-strip
/usr/bin/clang
/usr/bin/llvm-strip
```

**Comment by timraymond** [comment] 2024-11-20 17:08
Spoke with @SRodi offline about this. My working theory on the root cause of this is the re-entrant invocation of the Go toolchain with `go generate`. When `GOARCH=arm64 go generate ./pkg/plugin/...` happens, it invokes the `go run github.com/x/y/z/bpf2go@master` lines. This also receives `GOARCH=arm64`, and builds the arm64 version of `bpf2go`. It then tries to run it and fails because it's an amd64 system.

I don't think `go generate` was ever intended to be used with `go run` embedded in it. I think the solution will be to remove the `go run` parts. A workaround could be to `go install` the tools ahead of time.

**Comment by SRodi** [comment] 2024-12-11 17:30
@timraymond the issue appears to be with `toolchain go1.23.1`. I have upgraded to `toolchain go1.23.3` and it works fine.

```sh
❯ make generate-bpf-go
for arch in amd64 arm64; do \
        GOARCH=$arch go generate ./pkg/plugin/...; \
    done
Compiled /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_x86.o
Stripped /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_x86.o
Wrote /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_x86.go
/home/srodi/src/retina/pkg/plugin/dropreason/_cprog/drop_reason.c:205:13: warning: unused function 'get_packet_from_sock' [-Wunused-function]
static void get_packet_from_sock(struct packet *p, struct sock *sk)
            ^
1 warning generated.
Compiled /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_x86.o
Stripped /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_x86.o
Wrote /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_x86.go
Compiled /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_x86.o
Stripped /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_x86.o
Wrote /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_x86.go
Compiled /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_x86.o
Stripped /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_x86.o
Wrote /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_x86.go
Compiled /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_x86.o
Stripped /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_x86.o
Wrote /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_x86.go
Compiled /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_arm64.o
Stripped /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_arm64.o
Wrote /home/srodi/src/retina/pkg/plugin/conntrack/conntrack_bpfel_arm64.go
/home/srodi/src/retina/pkg/plugin/dropreason/_cprog/drop_reason.c:205:13: warning: unused function 'get_packet_from_sock' [-Wunused-function]
static void get_packet_from_sock(struct packet *p, struct sock *sk)
            ^
1 warning generated.
Compiled /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_arm64.o
Stripped /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_arm64.o
Wrote /home/srodi/src/retina/pkg/plugin/dropreason/kprobe_bpfel_arm64.go
Compiled /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_arm64.o
Stripped /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_arm64.o
Wrote /home/srodi/src/retina/pkg/plugin/filter/filter_bpfel_arm64.go
Compiled /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_arm64.o
Stripped /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_arm64.o
Wrote /home/srodi/src/retina/pkg/plugin/packetforward/packetforward_bpfel_arm64.go
Compiled /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_arm64.o
Stripped /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_arm64.o
Wrote /home/srodi/src/retina/pkg/plugin/packetparser/packetparser_bpfel_arm64.go
```

**Comment by timraymond** [comment] 2024-12-16 16:26
Closing since this seems to be fixed by upgrade

**Closed by timraymond** 2024-12-16 16:26 UTC
Labels: meta/invalid, lang/go
